site_name: Meu conhecimento blog
repo_url: https://github.com/Eduardo-Milagres/meu-conhecimento-blog
repo_name: meu-conhecimento-blog
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR
markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji  # Suporte a emojis
  - pymdownx.tasklist  # Suporte para tarefas
  - pymdownx.mark  # Suporte para marcações
  - pymdownx.tilde  # Suporte a tachado
  - pymdownx.highlight  # Suporte a código
plugins:
  - macros
  - search
  - callouts

extra:
  nomes:
    github_doc_repo: documentacao_gimi
  links:
    download_inventor_estudante: 'https://www.autodesk.com/education/gateway?sorting=featured&filters=individual'
  imagens:
    python_instalacao: <img src='/assets/images/instalacao_python.png'>